//TODO REFORMAT EVERYTHING
//TODO OPTIMIZE PERPIXELRENDERER TO BE USABLE
                //* OR *\\
//TODO FIX THE TEXTURE RENDERING METHOD TO USE WITH THE SHAPE RENDERER
//* TEXTURE RENDERING FOR SHAPE RENDERER METHOD:
//* CREATE A SEPARATE OFF SCREEN CANVAS WITH THE WIDTH AND HEIGHT OF THE TEXTURE
//* TRANSFORM IT TO HAVE THE SAME SIZE AND PERSPECTIVE AS THE SURFACE IT IS PROJECTED ON TO
//* I HAVE NO IDEA HOW TO DO THIS BECAUSE THE ALL VALUES IN CTX.TRANSFORM USE SCALAR VALUES BETWEEN 0 & 1 AMONG OTHER FACTORS